name: CXRISCV CI

on:
  workflow_dispatch:
  schedule:
  - cron: '30 * * * *'
  push:
    paths-ignore:
    - 'README.md'
    - '.devcontainer/**'
    - '.vscode/**'

env:
  # Set IAR_LMS_BEARER_TOKEN on: 
  # - GitHub Actions: https://github.com/<user|org>/riscv-board-examples/settings/secrets/actions
  # - GitHub Codespaces: https://github.com/<user|org>//riscv-board-examples/settings/secrets/codespaces
  # - Local Machine: export IAR_LMS_BEARER_TOKEN=<your-secret-CI-token>
  IAR_LMS_BEARER_TOKEN: ${{ secrets.IAR_LMS_BEARER_TOKEN }}

jobs:
  build-ninja-multi:
    name: Build Ninja Multi-Config
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/iarsystems/riscv
    steps:
    - name: Invoke the IAR C/C++ Compiler for RISC-V
      run: iccriscv --version
    - name: Checkout project
      uses: actions/checkout@v6
    - name: CMake - Configure Ninja Multi-Config preset
      run: cmake --preset ninja-multi
    - name: CMake - Build Debug preset
      run: cmake --build --preset debug-ninja-multi --verbose
    - name: CMake - Build Release preset
      run: cmake --build --preset release-ninja-multi --verbose
    - name: CMake - Build Release With Debug Info preset
      run: cmake --build --preset relwithdebinfo-ninja-multi --verbose
    - name: CMake - Build Minimum Size Release preset
      run: cmake --build --preset minsizerel-ninja-multi --verbose
    - name: CMake - Build Medium Speed preset
      run: cmake --build --preset medium-ninja-multi --verbose
    - name: CMake - Build High Speed preset
      run: cmake --build --preset highspeed-ninja-multi --verbose
    - name: CMake - Build Maximum Speed preset
      run: cmake --build --preset maxspeed-ninja-multi --verbose

  build-ninja:
    name: Build Ninja
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/iarsystems/riscv
    steps:
    - name: Invoke the IAR C/C++ Compiler for RISC-V
      run: iccriscv --version
    - name: Checkout project
      uses: actions/checkout@v6
    - name: CMake - Configure Ninja preset
      run: cmake --preset ninja
    - name: CMake - Build Debug preset
      run: cmake --build --preset debug-ninja --clean-first --verbose
    - name: CMake - Build Release preset
      run: cmake --build --preset release-ninja --clean-first --verbose
    - name: CMake - Build Release With Debug Info preset
      run: cmake --build --preset relwithdebinfo-ninja --clean-first --verbose
    - name: CMake - Build Minimum Size Release preset
      run: cmake --build --preset minsizerel-ninja --clean-first --verbose
    - name: CMake - Build Medium Speed preset
      run: cmake --build --preset medium-ninja --clean-first --verbose
    - name: CMake - Build High Speed preset
      run: cmake --build --preset highspeed-ninja --clean-first --verbose
    - name: CMake - Build Maximum Speed preset
      run: cmake --build --preset maxspeed-ninja --clean-first --verbose
